<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LoopQuest.Application\LoopQuest.Application.csproj" />
    <ProjectReference Include="..\LoopQuest.Infrastructure\LoopQuest.Infrastructure.csproj" />
    <ProjectReference Include="..\LoopQuest.ServiceDefaults\LoopQuest.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
